### ISSUE TITLE
Integrate textmodels into quanteda's pkgdown site

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.textmodels#11]
So that it will work as before.

I think this is possibleby linking the external (external = quanteda.textmodels) functions in quanteda's pkgdown site, via the instructions in https://cran.r-project.org/web/packages/pkgdown/vignettes/linking.html. See also https://cran.r-project.org/web/packages/pkgdown/vignettes/pkgdown.html#reference.  

I'm hoping that a version of this will work in **quanteda**'s `_pkgdown.yml` file:
```
  - title: "Test"
    desc: >
      Functions in another package
    contents: 
      - pkgA::func
```
